### ISSUE TITLE
Fixing StackOverFlow issue due to LomBok

### ISSUE THREAD

**Issue by Nagenderr2Code** [Nagenderr2Code/spring-recipe-app#8]

**Comment by Nagenderr2Code** [comment]
Due to Bi-directional dependencies. Equal & Hash code generation will throw 
java.lang.StackOverflowError: null
	at java.util.HashSet.iterator(HashSet.java:172) ~[na:1.8.0_131]
	at java.util.AbstractSet.hashCode(AbstractSet.java:122) ~[na:1.8.0_131]

By defining below annotation will solve this issue.
 
@EqualsAndHashCode(exclude = {"recipes"})
